ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Controllers/AdminRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shoplinhkien.Models;

namespace Shoplinhkien.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminRolesController : Controller
    {
        private readonly ShoplinkkienContext _context;
        public INotyfService _notyfService { get; }

        public AdminRolesController(ShoplinkkienContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminRoles
        public async Task<IActionResult> Index()
        {
            //return _context.Roles != null ? 
            //            View(await _context.Roles.ToListAsync()) :
            //            Problem("Entity set 'ShoplinkkienContext.Roles'  is null.");
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Admin/AdminRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //if (id == null || _context.Roles == null)
            //{
            //    return NotFound();
            //}

            //var role = await _context.Roles
            //    .FirstOrDefaultAsync(m => m.RoleId == id);
            //if (role == null)
            //{
            //    return NotFound();
            //}

            //return View(role);
            if (id == null)
            {
                return NotFound();
            }
            var role = await _context.Roles.FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Descriptiton")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //if (id == null || _context.Roles == null)
            //{
            //    return NotFound();
            //}

            //var role = await _context.Roles.FindAsync(id);
            //if (role == null)
            //{
            //    return NotFound();
            //}
            //return View(role);
            if (id == null)
            {
                return NotFound();
            }
            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Descriptiton")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        _notyfService.Success("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //if (id == null || _context.Roles == null)
            //{
            //    return NotFound();
            //}

            //var role = await _context.Roles
            //    .FirstOrDefaultAsync(m => m.RoleId == id);
            //if (role == null)
            //{
            //    return NotFound();
            //}

            //return View(role);
            if (id == null)
            {
                return NotFound();
            }
            var role = await _context.Roles.FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //if (_context.Roles == null)
            //{
            //    return Problem("Entity set 'ShoplinkkienContext.Roles'  is null.");
            //}
            //var role = await _context.Roles.FindAsync(id);
            //if (role != null)
            //{
            //    _context.Roles.Remove(role);
            //}

            //await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa quyền truy cập thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            //return (_context.Roles?.Any(e => e.RoleId == id)).GetValueOrDefault();
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Views/AdminRoles/Create.cshtml
@model Shoplinhkien.Models.Role

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriptiton" class="control-label"></label>
                <input asp-for="Descriptiton" class="form-control" />
                <span asp-validation-for="Descriptiton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model Shoplinhkien.Models.Role

@{
    ViewData["Title"] = "Xác nhận xóa quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@*<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descriptiton)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descriptiton)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="RoleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>*@
<h4 class="fw-bold py-3 mb-4">
    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="text-muted fw-light">Home / </a>
    <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="text-muted fw-light">Danh sách quyền truy cập /</a>

    <span class="text-muted fw-light">Xác nhận xóa quyền truy cập</span>
</h4>
<div class="card">

    <h5 class="card-header">Xác nhận xóa quyền truy cập</h5>
    <div class="table-responsive text-nowrap">
        <table class="table">
            <thead>
                <tr>
                    <td>ID:</td>
                    <td>@Model.RoleId</td>

                </tr>
                <tr>
                    <th>Tên quyền truy cập:</th>
                    <th>@Model.RoleName</th>

                </tr>
                <tr>
                    <th>Mô tả:</th>
                    <th>@Model.Descriptiton</th>

                </tr>
                <tr>
                    <th>Xác nhận xóa:</th>
                    <td>
                        <form asp-action="Delete" asp-route-id="@Model.RoleId">
                            <input type="hidden" asp-for="RoleId" />
                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                        </form>
                    </td>

                </tr>
            </thead>


        </table>
    </div>
</div>

ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Views/AdminRoles/Details.cshtml
@model Shoplinhkien.Models.Role

@{
    ViewData["Title"] = "Thông tin quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<h4 class="fw-bold py-3 mb-4">
    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="text-muted fw-light">Home / </a>
    <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="text-muted fw-light">Danh sách quyền truy cập /</a>

    <span class="text-muted fw-light">Thông tin quyền truy cập</span>
</h4>
<div class="card">

    <h5 class="card-header">Thông tin quyền truy cập</h5>
    <div class="table-responsive text-nowrap">
        <table class="table">
            <thead>
                <tr>
                    <td>ID:</td>
                    <td>@Model.RoleId</td>

                </tr>
                <tr>
                    <th>Tên quyền truy cập:</th>
                    <th>@Model.RoleName</th>

                </tr>
                <tr>
                    <th>Mô tả:</th>
                    <th>@Model.Descriptiton</th>

                </tr>
            </thead>


        </table>
    </div>
</div>

ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model Shoplinhkien.Models.Role

@{
    ViewData["Title"] = "Chỉnh sửa quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<!-- Basic Layout -->
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="text-muted fw-light">Home / </a>
        <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="text-muted fw-light">Danh sách quyền truy cập /</a>

        <span class="text-muted fw-light">Chỉnh sửa quyền truy cập</span>
    </h4>
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Chỉnh sửa quyền truy cập</h5>
                    <small class="text-muted float-end">Merged input group</small>
                </div>
                <div class="card-body">
                    <form asp-action="Edit" asp-route-id="@Model.RoleId" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="RoleId" />
                        <div class="mb-3">
                            <label class="form-label" for="basic-icon-default-fullname">Role Name</label>
                            <div class="input-group input-group-merge">
                                <span id="basic-icon-default-fullname2" class="input-group-text">
                                    <i class="bx bx-user"></i>
                                </span>
                                <input type="text"
                                       class="form-control"
                                       id="basic-icon-default-fullname"
                                       placeholder="Role Name"
                                       asp-for="RoleName"
                                       aria-label="Role Name"
                                       aria-describedby="basic-icon-default-fullname2" />
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" asp-for="Descriptiton" for="basic-icon-default-company">Description</label>
                            <div class="input-group input-group-merge">
                                <span id="basic-icon-default-company2" class="input-group-text">
                                    <i class="bx bx-buildings"></i>
                                </span>
                                <input type="text"
                                       id="basic-icon-default-company"
                                       class="form-control"
                                       asp-for="Descriptiton"
                                       placeholder="Description"
                                       aria-label="Description"
                                       aria-describedby="basic-icon-default-company2" />
                            </div>
                        </div>



                        <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ShoplinhkienTimKiemSanPham/Shoplinhkien/Shoplinhkien/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<Shoplinhkien.Models.Role>

@{
    ViewData["Title"] = "Quản lý quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-body" style="position:absolute; right:0; ">

        <div class="demo-inline-spacing">
            <a class="btn btn-primary" asp-controller="AdminRoles" asp-action="Create">Add Roles</a>
        </div>
    </div>
    <h5 class="card-header">Account</h5>
    <div class="">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>@item.RoleId</strong></td>
                            <td>
                                @item.RoleName
                            </td>
                            <td>
                                @item.Descriptiton
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                        <i class="bx bx-dots-vertical-rounded"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit" asp-route-id="@item.RoleId"><i class="bx bx-edit-alt me-1"></i> Edit</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Details" asp-route-id="@item.RoleId"><i class="bx bx-trash me-1"></i> Details</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Delete" asp-route-id="@item.RoleId"><i class="bx bx-trash me-1"></i> Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>

        </table>
    </div>
</div>